apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2024-11-22T15:56:01Z"
  generation: 10
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 5ebbe82f-d253-4be4-ba87-ff8759c0d16d
  resourceVersion: "3828317"
  uid: 7f54a934-643b-4354-a259-b780a0ba5347
spec:
  identityProviders:
  - gitlab:
      clientID: "1234"
      clientSecret:
        name: gitlab-client-secret-5957f
      url: https://test.fake.com
    mappingMethod: claim
    name: GITLAB-GitOPs
    type: GitLab
