apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    app.kubernetes.io/instance: ldap-test
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
spec:
  identityProviders:
  - gitlab:
      clientID: "1234"
      clientSecret:
        name: gitlab-client-secret-5957f
      url: https://test.fake.com
    mappingMethod: claim
    name: GITLAB-GitOPs
    type: GitLab
